import os
import tempfile
import io

import matplotlib.pyplot as plt

from reportlab.platypus import SimpleDocTemplate, Paragraph, Image
from reportlab.lib.styles import getSampleStyleSheet


from datetime import datetime

# ------------------------------------------------------------------
# Shared PDF report helpers
# Reused across different PDF generation implementations.
# ------------------------------------------------------------------

def get_report_timestamp():
    """
    Generate a consistent timestamp for all PDF reports.
    """
    return datetime.now().strftime("%d-%m-%Y %H:%M")


def generate_summary(positive, negative):
    """
    Generate a high-level sentiment summary.
    """
    if positive > negative:
        return "Overall customer sentiment is favorable."

    return "Customer feedback indicates improvement areas in service."


def generate_insight(positive, negative):
    """
    Generate key business insight based on sentiment distribution.
    """
    if positive > negative:
        return (
            "Customer sentiment is mostly positive. "
            "Customers appear satisfied with the service experience."
        )

    return (
        "Negative sentiment is higher than positive sentiment. "
        "This suggests improvements are needed in customer experience."
    )


def generate_recommendation(positive, negative):
    """
    Generate actionable recommendation based on sentiment analysis.
    """
    if negative > positive:
        return (
            "Focus on resolving recurring complaints and improving "
            "customer support response time."
        )

    return (
        "Maintain current service quality and continue monitoring "
        "customer satisfaction trends."
    )

def create_pdf(total, positive, negative, chart_path):

    pdf = FPDF()

    pdf.add_page()

    # Title
    pdf.set_fill_color(200, 220, 255)

    pdf.set_font("Arial", "B", 16)

    pdf.cell(
        0,
        12,
        "Business Health Overview",
        ln=True,
        fill=True
        )
    pdf.ln(10)

    # Overview Section
    pdf.set_font("Arial", "B", 14)
    

    pdf.ln(5)

    pdf.set_font("Arial", size=12)

    pdf.cell(200, 10, f"Total Reviews: {total}", ln=True)
    pdf.cell(200, 10, f"Positive Reviews: {positive}", ln=True)
    pdf.cell(200, 10, f"Negative Reviews: {negative}", ln=True)

    pdf.ln(10)
    current_time = get_report_timestamp()

    pdf.cell(200, 10, f"Generated On: {current_time}", ln=True)    

    # Summary
    summary = generate_summary(
        positive,
        negative
    )
    pdf.multi_cell(0, 10, f"Summary: {summary}")
    

    if os.path.exists(chart_path):
        pdf.ln(5)
        pdf.image(chart_path, x=45, w=100)
    #Insights
    pdf.ln(5)

    pdf.set_font("Arial", "B", 13)
    pdf.cell(200, 10, "Key Insights", ln=True)

    pdf.set_font("Arial", "", 11)

    insight = generate_insight(
    positive,
    negative
   )

    pdf.multi_cell(0, 8, insight)


#Recommendations
    pdf.ln(5)

    pdf.set_font("Arial", "B", 13)
    pdf.cell(200, 10, "Recommendations", ln=True)

    pdf.set_font("Arial", "", 11)

    recommendation = generate_recommendation(
    positive,
    negative
    )
    
    pdf.multi_cell(0, 8, recommendation)

    pdf.ln(10)

    pdf.set_font("Arial", "I", 10)

    pdf.cell(
        0,
        10,
        "Generated by BizInsight AI",
        ln=True,
        align="R"
    )

    # Save PDF
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_pdf:
        pdf_path = tmp_pdf.name

    pdf.output(pdf_path)

    return pdf_path

# ------------------------------------------------------------------
# Streamlit analytics report generator
# Centralized PDF generation service used by dashboard exports
# ------------------------------------------------------------------

   
def generate_report_pdf(df, trend, keywords):
    buffer = io.BytesIO()
    pdf = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()
    content = []

    content.append(Paragraph("BizInsight AI Report", styles["Title"]))
    content.append(Paragraph("Generated: " + get_report_timestamp(), styles["Normal"]))
    content.append(Paragraph("Total Reviews: " + str(len(df)), styles["Normal"]))
    content.append(Paragraph("Positive: " + str((df["sentiment"] > 0).sum()), styles["Normal"]))
    content.append(Paragraph("Negative: " + str((df["sentiment"] < 0).sum()), styles["Normal"]))

    fig1, ax1 = plt.subplots()
    ax1.plot(trend.index, trend.values)
    ax1.set_title("Sentiment Trend")
    img1 = io.BytesIO()
    fig1.savefig(img1, format="png")
    plt.close(fig1)
    img1.seek(0)
    content.append(Image(img1, width=400, height=200))

    fig2, ax2 = plt.subplots()
    ax2.bar(["Positive", "Negative"], [(df["sentiment"] > 0).sum(), (df["sentiment"] < 0).sum()])
    ax2.set_title("Positive vs Negative")
    img2 = io.BytesIO()
    fig2.savefig(img2, format="png")
    plt.close(fig2)
    img2.seek(0)
    content.append(Image(img2, width=400, height=200))

    content.append(Paragraph("Top Keywords: " + ", ".join(keywords), styles["Normal"]))
    pdf.build(content)
    buffer.seek(0)
    return buffer.read() 
